version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        container_name: 'mysql'
        working_dir: /application
        volumes:
            - 'my-db:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=forge
            - MYSQL_USER=forge
            - MYSQL_PASSWORD=forge
        ports:
            - '3306:3306'
            - '11002:3307'
            - '33306:3307'
        networks:
            - internal

    webserver:
        image: 'nginx:alpine'
        container_name: 'nginx'
        working_dir: /application
        volumes:
            - './src:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '11000:80'
        networks:
            - internal

    php-fpm:
        container_name: 'php'
        build: phpdocker/php-fpm
        working_dir: /application
        tty: true
        volumes:
            - './src:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
            - './supervisord.conf:/etc/supervisor/conf.d/supervisord.conf'
        networks:
            - internal

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 'pma'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - PMA_HOST=mysql
            - UPLOAD_LIMIT=5G
        depends_on:
            - mysql
        links:
            - mysql
        ports:
            - "8082:80"
        networks:
            - internal

# Names our volume
volumes:
    my-db:
        driver: local

# Networks
networks:
    internal:
        driver: bridge